name: winc_dart_custom_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  custom_lint_builder: ^0.7.5
  analyzer: ^7.3.0
  collection: ^1.19.1
  analyzer_plugin: ^0.13.0
  meta: ^1.16.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

